[versions]
junitVersion = "6.1.1"
checkstyleVersion = "13.7.0"
aeronVersion = "1.52.0"
sbeVersion = "1.39.0"
agronaVersion = "2.5.0"
slf4jVersion = "2.0.18"
logbackVersion = "1.5.37"
mockitoVersion = "5.23.0"
jmhVersion = "1.37"
picocliVersion = "4.7.7"
jlineVersion = "3.30.6"
picoJlineVersion = "4.7.7"
versionsVersion = "0.54.0"

[libraries]
aeron-archive = { group = "io.aeron", name = "aeron-archive", version.ref = "aeronVersion" }
aeron-samples = { group = "io.aeron", name = "aeron-samples", version.ref = "aeronVersion" }
agrona = { group = "org.agrona", name = "agrona", version.ref = "agronaVersion" }
sbe = { group = "uk.co.real-logic", name = "sbe-tool", version.ref = "sbeVersion" }
jupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitVersion" }
jupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitVersion" }
jupiterPlatform = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junitVersion" }
checkstyle = { group = "com.puppycrawl.tools", name = "checkstyle", version.ref = "checkstyleVersion" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4jVersion" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logbackVersion" }
mockito-core = { group = "org.mockito", name="mockito-core", version.ref = "mockitoVersion"}
mockito-junit = { group = "org.mockito", name="mockito-junit-jupiter", version.ref = "mockitoVersion"}
jmhcore = { group = "org.openjdk.jmh", name = "jmh-core", version.ref = "jmhVersion" }
jmhannprocess = { group = "org.openjdk.jmh", name = "jmh-generator-annprocess", version.ref = "jmhVersion" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocliVersion" }
jline = { group = "org.jline", name = "jline", version.ref = "jlineVersion" }
picoJline = { group = "info.picocli", name = "picocli-shell-jline3", version.ref = "picoJlineVersion" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsVersion" }

[bundles]
testing = [ "jupiterApi", "jupiterEngine", "jupiterPlatform", "mockito-core", "mockito-junit"]
